config/routes.rb
Sian::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root to: 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'terms_of_service' => 'pages#terms_of_service'
  get 'privacy_policy' => 'pages#privacy_policy'

  get 'home_en' => 'pages#home_en'
  get 'about_us_en' => 'pages#about_us_en'
  
  resources :properties, only: [:index, :show, :create]
  resources :properties_en, only: [:index, :show, :create]

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  match 'contact_en' => 'contact_en#new', :as => 'contact_en', :via => :get
  match 'contact_en' => 'contact_en#create', :as => 'contact_en', :via => :post

  match 'newsletters' => 'newsletters#create', :as => 'newsletters', :via => :post
  match 'newsletters_en' => 'newsletters_en#create', :as => 'newsletters_en', :via => :post
  

end

app/models/property.rb
class Property < ActiveRecord::Base
  validate :name, presence: true
  has_many :images, as: :viewable, order: :position, :dependent => :destroy
  has_many :documents
  attr_protected
  accepts_nested_attributes_for :images, :documents, allow_destroy: true
  validates :url_name, uniqueness: true
  validates :name, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  before_validation do
    return if self.name.blank?
    self.url_name = self.name.downcase.gsub(/[^a-z0-9]/,'-')
  end
end  

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    if params[:type_of_property] == nil
      @type_of_property = 'Luxury Properties'
    else
      @type_of_property = params[:type_of_property]
    end

    if params[:country] == 'Todos los paises' || params[:country] == 'Seleccione el pais'|| params[:country] == nil 
      @country = 0
    else
      @country = params[:country]
    end

    if params[:location] == 'Todos los barrios' || params[:location] == 'Seleccione el barrio' || params[:location] == nil 
      @location = 0
    else
      @location = params[:location]
    end
    

    if params[:type_of_operation] == 'Todas las operaciones' || params[:type_of_operation] == 'Seleccione tipo de operacion' || params[:type_of_operation] == nil 
      @type_of_operation = 0
    else
      @type_of_operation = params[:type_of_operation]
    end

    if params[:code]
      @properties = Property.find(:all, :order => 'prioridad asc', :conditions => {:code => params[:code]})
    else  
      @properties = Property.where(:type_of_property => @type_of_property).where(:country => @country).where(:location => @location).where(:type_of_operation => @type_of_operation).where(:state => 'Publicada').order('prioridad asc')
    end

  end
  
  def show
    @property = Property.find(params[:id])
    @covered = @property.covered_square_meters
    @uncovered = @property.uncovered_square_meters
    unless @property.ambientes.nil? 
      @ambientes = @property.ambientes.split(/\r\n/) 
    end
    unless @property.amenities.nil?
      @amenities = @property.amenities.split(/\r\n/) 
    end
    @message = Message.new
  end

 def create

    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message_property(@message).deliver
      redirect_to(properties_path(@property), :notice => "Mensaje enviado correctamente.")
    else
      flash.now.alert = "Por favor, rellene todos los campos."
      render :new
    end
  end

end

app/views/properties/index.html.haml
.row-fluid.propicons
  %ul
    %li
      = link_to('', properties_path(:type_of_property => 'Luxury Properties'), :class => 'luxury')
      %h4 Luxury
      %h4 Properties
    %li
      = link_to('', properties_path(:type_of_property => 'Urban Properties'), :class => 'urban')
      %h4 Urban
      %h4 Properties
    %li
      = link_to('', properties_path(:type_of_property => 'Commercial Properties'), :class => 'commercial')
      %h4 Commercial
      %h4 Properties
    %li
      = link_to('', properties_path(:type_of_property => 'Campos & Counrty Clubs'), :class => 'campos')
      %h4 Campos &
      %h4 Country-Clubs
    %li
      = link_to('', properties_path(:type_of_property => 'Developments'), :class => 'developments')
      %h4 Desarollos
      %h4 Lotes
  = semantic_form_for "", url: properties_path, :html => {:method => :get} do |f|
    .row-fluid
      = f.input :type_of_property, :as => :hidden, :input_html => {:value => @type_of_property}
      .smallselect.span3(style="margin-left:0px;")
        .selectmask
          = f.input :country, :as => :select, :include_blank => false, :label => false, :collection => options_for_select(['Seleccione el pais','Todos los paises', 'Argentina', 'Uruguay', 'USA'],'Seleccione el pais'), :input_html => {:class =>'drop', :autocomplete => :off}
      .smallselect.span4#arg
        .selectmask
          = f.input :location, :as => :select, :include_blank => false, :label => false, :collection => options_for_select(["Seleccione el barrio","Todos los barrios","CABA", "Zona Norte", "Gran Buenos Aires", "Interior del País"], 'Seleccione el barrio'), :input_html => {:class =>'drop', :autocomplete => "off"}
      .smallselect.span4
        .selectmask
          = f.input :type_of_operation, :include_blank => false, :label => false, :as => :select, :collection => options_for_select(["Seleccione tipo de operacion","Todas las operaciones", "Venta", "Alquiler", "Desarrollos"], 'Seleccione tipo de operacion'), :input_html => {:class =>'drop', :autocomplete => "off"}
      .span1.applyfilters
        = f.button :Buscar
.row-fluid.container
  - if @properties.empty?
    %p La busqueda no arrojó ningún resultado
  - else
    - @properties.each do |property|
      .span4
        = link_to(property_path(property)) do
          .item
            .ph
              - if property.images.empty? 
                = image_tag('image-not-available.png')
              - else
                - property.images.each do |image|
                  - if image.cover == true
                    = image_tag(image.file.url(:large))
                
            %h5 #{property.name}
            .line
            %p #{property.price}
            .bottomDetail
              %h4 Ver detalle +
:javascript
  $(function() {
    if('#{@country}'!=0){
      $("select#country option:selected").removeAttr("selected");
      $("select#country option[value='#{@country}']").attr("selected","selected");
    }else{
      $("select#country option:selected").removeAttr("selected");
      $("select#country option[value='Todos los paises']").attr("selected","selected");
    }
    country = $('select#country option:selected').val();
    changeCountry(country);

    if('#{@location}'!=0){
      $("select#location option:selected").removeAttr("selected");
      $("select#location option[value='#{@location}']").attr("selected","selected");
    }else{
      $("select#location option:selected").removeAttr("selected");
      $("select#location option[value='Todos los barrios']").attr("selected","selected");
    }

    if('#{@type_of_operation}'!=0){
      $("select#type_of_operation option:selected").removeAttr("selected");
      $("select#type_of_operation option[value='#{@type_of_operation}']").attr("selected","selected");
    }else{
      $("select#type_of_operation option:selected").removeAttr("selected");
      $("select#type_of_operation option[value='Todas las operaciones']").attr("selected","selected");
    }

    $('select#country').change(function(){
      countryChange = $(this).val();
      changeCountry(countryChange);
    });
  });

  function changeCountry(country){
    switch(country){
      case 'Argentina':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="CABA">CABA</option><option value="Zona Norte">Zona Norte</option><option value="Gran Buenos Aires">Gran Buenos Aires</option><option value="Interior del País">Interior del País</option>');
        break;
      case 'Uruguay':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="Punta del Este">Punta del Este</option><option value="Montevideo">Montevideo</option><option value="Otras">Otras</option>');
        break;
      case 'USA':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="Miami">Miami</option><option value="New York">New York</option><option value="Otras">Otras</option>');
        break;
    }
  }

app/views/properties/show.html.haml
.row-fluid
  .row-fluid
    %h1(style="margin-bottom:0;") #{@property.name}
  .row-fluid
    %h5 #{@property.public_address}
  .row-fluid(style="margin-top:50px;")
    = render "sliderShow"
    .span4.detalles
      - unless @property.price.empty?
        %h2 #{@property.price}.-
      -else
        %h6 Consulta por esta propiedad
      %p
        Envíenos un mensaje si desea recibir mas información sobre esta propiedad.
      = semantic_form_for @message, :url => properties_path(@property) do |f|
        = f.input :property, :as => :hidden, :input_html => {:value => @property.name} 
        = f.input :name, :label => false, :input_html => {:placeholder => "Nombre"}
        = f.input :phone, :label => false, :input_html => {:placeholder => "Teléfono"}
        = f.input :email, :label => false, :input_html => {:placeholder => "E-mail"}
        = f.input :body, :as => :text,:label => false, :input_html => {:placeholder => "Comentarios...", :rows => 4}
        = f.button :Enviar, :class => 'do-form'
      %input{:type => 'checkbox', :class => 'humancheck'} Estoy listo para enviar mi consulta
.row-fluid
  %h1(style="margin-top:0px;") Descripción
  %p #{@property.description}
.row-fluid.desc
  .span4
    %h5 Características Generales
    %ul
      -if defined? @covered and @uncovered
        %li Superficie total: #{@covered + @uncovered}
        %li Metros cubiertos: #{@property.covered_square_meters}
        %li Metros descubiertos: #{@property.uncovered_square_meters}
        %li Cant. Habitaciones: #{@property.rooms}
        %li Cant. baños: #{@property.bathrooms}
        %li Cant. toilettes: #{@property.toilette}
        %li Ubicación en planta: #{@property.ubicacion_en_planta}
        %li Estado: #{@property.estado}
        %li Luminosidad: #{@property.luminosidad}
  .span4
    %h5 Características del edificio
    %ul
      %li  Categoría: #{@property.categoria}
      %li  Pisos: #{@property.pisos}
  .span4
    %h5 Ambientes
    %ul
      - unless @ambientes.nil?
        - @ambientes.each do |ambiente|
          %li #{ambiente}
.row-fluid.desc
  .span4
    %h5 Servicios
    %ul
      %li Agua caliente: #{@property.agua_caliente}
      %li Calefacción: #{@property.calefaccion}
      %li Aire acondicionado: #{@property.aire_acondicionado}
  .span4
    %h5 Amenities
    %ul
      - unless @amenities.nil?
        - @amenities.each do |amenity|
          %li #{amenity} 
  .span4
    %h5 Entorno y puntos de interés
    %ul
      %li #{@property.puntos_interes}
.row-fluid
  %h1 Ubicación
  #map_canvas
.row-fluid.pdfsbox
  - unless @property.documents.empty?
    %h6 Documentos relacionados
    - @property.documents.each do |doc|
      = link_to doc.file_file_name, doc.file.url, target: '_blank'
  
  

:javascript
  $('.do-form').hide();
  $('.humancheck').click(function(event){
    $('.do-form').fadeToggle();
  });
  myCenter = new google.maps.LatLng(#{@property.latitude}, #{@property.longitude});
  function initialize() {

      var mapOptions = {
        center: myCenter,
        zoom: 16,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map_canvas"),
          mapOptions);
      var marker=new google.maps.Marker({
        position:myCenter,
      });

      marker.setMap(map);

    }