config/routes.rb
Sian::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root to: 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'terms_of_service' => 'pages#terms_of_service'
  get 'privacy_policy' => 'pages#privacy_policy'

  get 'home_en' => 'pages#home_en'
  get 'about_us_en' => 'pages#about_us_en'
  
  resources :properties, only: [:index, :show, :create]
  resources :properties_en, only: [:index, :show, :create]

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  match 'contact_en' => 'contact_en#new', :as => 'contact_en', :via => :get
  match 'contact_en' => 'contact_en#create', :as => 'contact_en', :via => :post

  match 'newsletters' => 'newsletters#create', :as => 'newsletters', :via => :post
  match 'newsletters_en' => 'newsletters_en#create', :as => 'newsletters_en', :via => :post
  

end

app/controllers/properties_en_controller.rb
class PropertiesEnController < ApplicationController
  def index
    if params[:type_of_property] == nil
      @type_of_property = 'Luxury Properties'
    else
      @type_of_property = params[:type_of_property]
    end

    if params[:country] == 'Todos los paises' || params[:country] == 'Seleccione el pais'|| params[:country] == nil 
      @country = 0
    else
      @country = params[:country]
    end

    if params[:location] == 'Todos los barrios' || params[:location] == 'Seleccione el barrio' || params[:location] == nil 
      @location = 0
    else
      @location = params[:location]
    end
    

    if params[:type_of_operation] == 'Todas las operaciones' || params[:type_of_operation] == 'Seleccione tipo de operacion' || params[:type_of_operation] == nil 
      @type_of_operation = 0
    else
      @type_of_operation = params[:type_of_operation]
    end

    if params[:code]
      @properties = Property.find(:all, :order => 'prioridad asc', :conditions => {:code => params[:code]})
    else  
      @properties = Property.where(:type_of_property => @type_of_property).where(:country => @country).where(:location => @location).where(:type_of_operation => @type_of_operation).where(:state => 'Publicada').order('prioridad asc')
    end

  end
  
  def show
    @property = Property.find(params[:id])
    @covered = @property.covered_square_meters
    @uncovered = @property.uncovered_square_meters
    unless @property.ambientes_en.nil?
      @ambientes_en = @property.ambientes_en.split(/\r\n/) 
    end
    unless @property.property_amenities_en.nil?
      @amenities_en = @property.property_amenities_en.split(/\r\n/) 
    end
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message_property(@message).deliver
      redirect_to(properties_en_index_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/views/properties_en/_sliderShow.html.haml
#wrapper
  .span8
    %ul.bxslider
      - @property.images.each do |image|
        %li
          = image_tag(image.file.url(:large))
:javascript
  $(document).ready(function(){
    $('.bxslider').bxSlider({
      mode: 'fade'
    });
  });


    // agregar fotos de aspect cuadrado, no wide porque si no se va a ajustar al widescreen



    

app/views/properties_en/index.html.haml
.row-fluid.propicons
  %ul
    %li
      = link_to('', properties_en_index_path(:type_of_property => 'Luxury Properties'), :class => 'luxury')
      %h4 Luxury
      %h4 Properties
    %li
      = link_to('', properties_en_index_path(:type_of_property => 'Urban Properties'), :class => 'urban')
      %h4 Urban
      %h4 Properties
    %li
      = link_to('', properties_en_index_path(:type_of_property => 'Commercial Properties'), :class => 'commercial')
      %h4 Commercial
      %h4 Properties
    %li
      = link_to('', properties_en_index_path(:type_of_property => 'Campos & Counrty Clubs'), :class => 'campos')
      %h4 Campos &
      %h4 Country-Clubs
    %li
      = link_to('', properties_en_index_path(:type_of_property => 'Developments'), :class => 'developments')
      %h4 Desarollos
      %h4 Inmobiliarios
  = semantic_form_for "", url: properties_en_index_path, :html => {:method => :get} do |f|
    .row-fluid
      = f.input :type_of_property, :as => :hidden, :input_html => {:value => @type_of_property}
      .smallselect.span3(style="margin-left:0px;")
        .selectmask
          = f.input :country, :as => :select, :include_blank => false, :label => false, :collection => options_for_select(['Select Country','All Countries', 'Argentina', 'Uruguay', 'USA'],'Select Country'), :input_html => {:class =>'drop', :autocomplete => :off}
      .smallselect.span4#arg
        .selectmask
          = f.input :location, :as => :select, :include_blank => false, :label => false, :collection => options_for_select(["Select Location","All Locations","CABA", "Zona Norte", "Gran Buenos Aires", "Interior del País"], 'Select Location'), :input_html => {:class =>'drop', :autocomplete => "off"}
      .smallselect.span4
        .selectmask
          = f.input :type_of_operation, :include_blank => false, :label => false, :as => :select, :collection => options_for_select(["Select type of Operation","All types of Operation", "Venta", "Alquiler", "Desarrollos"], 'Select type of Operation'), :input_html => {:class =>'drop', :autocomplete => "off"}
      .span1.applyfilters
        = f.button :Search
.row-fluid.container
  - if @properties.empty?
    %p No results found for this search
  - else
    - @properties.each do |property|
      .span4
        = link_to(properties_en_path(property)) do
          .item
            .ph 
              - if property.images.empty? 
                = image_tag('image-not-available.png')
              - else
                - property.images.each do |image|
                  - if image.cover == true
                    = image_tag(image.file.url(:large))
            %h5 #{property.name}
            .line
            %p $#{property.price}.-
            .bottomDetail
              %h4 View more +
:javascript
  $(function() {
    if('#{@country}'!=0){
      $("select#country option:selected").removeAttr("selected");
      $("select#country option[value='#{@country}']").attr("selected","selected");
    }else{
      $("select#country option:selected").removeAttr("selected");
      $("select#country option[value='Todos los paises']").attr("selected","selected");
    }
    country = $('select#country option:selected').val();
    changeCountry(country);

    if('#{@location}'!=0){
      $("select#location option:selected").removeAttr("selected");
      $("select#location option[value='#{@location}']").attr("selected","selected");
    }else{
      $("select#location option:selected").removeAttr("selected");
      $("select#location option[value='Todos los barrios']").attr("selected","selected");
    }

    if('#{@type_of_operation}'!=0){
      $("select#type_of_operation option:selected").removeAttr("selected");
      $("select#type_of_operation option[value='#{@type_of_operation}']").attr("selected","selected");
    }else{
      $("select#type_of_operation option:selected").removeAttr("selected");
      $("select#type_of_operation option[value='Todas las operaciones']").attr("selected","selected");
    }

    $('select#country').change(function(){
      countryChange = $(this).val();
      changeCountry(countryChange);
    });   
  });

  function changeCountry(country){
    switch(country){
      case 'Argentina':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="CABA">CABA</option><option value="Zona Norte">Zona Norte</option><option value="Gran Buenos Aires">Gran Buenos Aires</option><option value="Interior del País">Interior del País</option>');
        break;
      case 'Uruguay':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="Punta del Este">Punta del Este</option><option value="Montevideo">Montevideo</option><option value="Otras">Otras</option>');
        break;
      case 'USA':
        $('select#location').children().remove();
        $('select#location').append('<option value="Seleccione el barrio" selected="selected">Seleccione el barrio</option><option value="Todos los barrios">Todos los barrios</option><option value="Miami">Miami</option><option value="New York">New York</option><option value="Otras">Otras</option>');
        break;
    }
  }

app/views/properties_en/show.html.haml
.row-fluid
  .row-fluid
    %h1(style="margin-bottom:0;") #{@property.name}
  .row-fluid
    %h5 #{@property.public_address}
  .row-fluid(style="margin-top:50px;")
    = render "sliderShow"
    .span4.detalles
      %h6 More about this property
      %p
        For more information send us a message.
      = semantic_form_for @message, :url => properties_en_index_path do |f|
        = f.input :property, :as => :hidden, :input_html => {:value => @property.name} 
        = f.input :name, :label => false, :input_html => {:placeholder => "Name"}
        = f.input :phone, :label => false, :input_html => {:placeholder => "Phone"}
        = f.input :email, :label => false, :input_html => {:placeholder => "E-mail"}
        = f.input :body, :as => :text,:label => false, :input_html => {:placeholder => "Comments...", :rows => 4}
        = f.button :Send, :class => 'do-form'
        %input{:type => 'checkbox', :class => 'humancheck'} I'm ready to send this form
.row-fluid
  %h1(style="margin-top:0px;") Description
  %p #{@property.property_description_en}
.row-fluid.desc
  .span4
    %h5 General characteristics
    %ul
      -if defined? @covered and @uncovered
        %li Square meters – Total: #{@covered + @uncovered}
        %li Square meters (Br metres)– indoor space: #{@property.covered_square_meters}
        %li Metros descubiertos: #{@property.uncovered_square_meters}
      %li Rooms: #{@property.rooms}
      %li Bathrooms: #{@property.bathrooms}
      %li Toilets: #{@property.toilette}
      %li Location in ground: #{@property.ubicacion_en_planta}
      %li Condition: #{@property.estado}
      %li Brightness: #{@property.luminosidad}
  .span4
    %h5 Building characteristics
    %ul
      %li Category: #{@property.categoria}
      %li Floors: #{@property.pisos}
  .span4
    %h5 Rooms
    %ul
      - unless @ambientes_en.nil?
        - @ambientes_en.each do |ambiente|
          %li #{ambiente}
.row-fluid.desc
  .span4
    %h5 Facilities
    %ul
      - if @property.agua_caliente == 'si' || @property.agua_caliente == 'Si'
        %li Hot water: Yes
      - else  
        %li Hot water: #{@property.agua_caliente}
      - if @property.calefaccion == 'si' || @property.calefaccion == 'Si' 
        %li Heating: Yes
      - else
        %li Heating: #{@property.calefaccion}
      - if @property.aire_acondicionado == 'si' || @property.aire_acondicionado == 'Si' 
        %li Air Conditioning: Yes
      - else
        %li Air Conditioning: #{@property.aire_acondicionado}
  .span4
    %h5 Amenities
    %ul
      -unless @amenities_en.nil?
        - @amenities_en.each do |amenity|
          %li #{amenity} 
  .span4
    %h5 Points of interest
    %ul
      %li #{@property.puntos_interes_en}
.row-fluid
  %h1 Location
  #map_canvas
.row-fluid.pdfsbox
  - unless @property.documents.empty?
    %h6 Related Documents
    - @property.documents.each do |doc|
      = link_to doc.file_file_name, doc.file.url, target: '_blank'
  

:javascript
  $('.do-form').hide();
  $('.humancheck').click(function(event){
    $('.do-form').fadeToggle();
  });
  myCenter = new google.maps.LatLng(#{@property.latitude}, #{@property.longitude});
  function initialize() {

      var mapOptions = {
        center: myCenter,
        zoom: 16,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map_canvas"),
          mapOptions);
      var marker=new google.maps.Marker({
        position:myCenter,
      });

      marker.setMap(map);

    }