config/routes.rb
Sian::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root to: 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'terms_of_service' => 'pages#terms_of_service'
  get 'privacy_policy' => 'pages#privacy_policy'

  get 'home_en' => 'pages#home_en'
  get 'about_us_en' => 'pages#about_us_en'
  
  resources :properties, only: [:index, :show, :create]
  resources :properties_en, only: [:index, :show, :create]

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
  match 'contact_en' => 'contact_en#new', :as => 'contact_en', :via => :get
  match 'contact_en' => 'contact_en#create', :as => 'contact_en', :via => :post

  match 'newsletters' => 'newsletters#create', :as => 'newsletters', :via => :post
  match 'newsletters_en' => 'newsletters_en#create', :as => 'newsletters_en', :via => :post
  

end

app/views/layouts/_footer.html.haml
%footer.footer
  .row-fluid
    .newsletter.span3
      %h4 NEWSLETTER
      =# render 'contact/new' 
      = semantic_form_for Newsletter.new, :url => newsletters_path do |f| 
        = f.input :name, :label => false, :input_html => {:placeholder => "Nombre"}
        = f.input :apellido, :label => false, :input_html => {:placeholder => "Apellido"}
        = f.input :email, :label => false, :input_html => {:placeholder => "E-mail"}
        = f.button :Enviar     
    .barrio.span7
      .span4
        %h4 BELGRANO
        %p
          Gorostiaga 1514  
          %br
          1426 - CABA
          %br
          Tel/Fax - 4774-1414
          %br
          4778-9600 / 4776-7544
          %br
          info@siangroup.net
      .span4
        %h4 BELGRANO
        %p
          Moldes 2276 
          %br
          C1428CRJ - CABA
          %br
          Tel/fax 4781-7000 y Rot.
          %br
          info@siangroup.net
      .span4
        %h4 ZONA NORTE
        %p
          San Lorenzo. 807
          %br
          La Lucila - 1636
          %br
          Pdo. Vicente López
          %br
          Tel/Fax - 4781-7000 y Rot.
          %br
          info@siangroup.net
    .social.span2
      %h4 SOCIAL
      .span12
        .twitter.span1
      .span12
        .facebook.span1
      

app/views/layouts/_footer_en.html.haml
%footer.footer
  .row-fluid
    .newsletter.span3
      %h4 NEWSLETTER
      = semantic_form_for Newsletter.new, :url => newsletters_en_path do |f| 
        = f.input :name, :label => false, :input_html => {:placeholder => "Nombre"}
        = f.input :apellido, :label => false, :input_html => {:placeholder => "Apellido"}
        = f.input :email, :label => false, :input_html => {:placeholder => "E-mail"}
        = f.button :Enviar     
    .barrio.span7
      .span4
        %h4 BELGRANO
        %p
          Gorostiaga 1514  
          %br
          1426 - CABA
          %br
          Tel/Fax - 4774-1414
          %br
          4778-9600 / 4776-7544
          %br
          info@siangroup.net
      .span4
        %h4 BELGRANO
        %p
          Moldes 2276 
          %br
          C1428CRJ - CABA
          %br
          Tel/fax and lines
          %br
          4781-7000 y Rot.
          %br
          info@siangroup.net
      .span4
        %h4 NORTHERN AREA
        %p
          San Lorenzo. 807
          %br
          La Lucila - 1636
          %br
          Pdo. Vicente López
          %br
          Tel/Fax - 4781-7000 y Rot.
          %br
          info@siangroup.net
    .social.span2
      %h4 SOCIAL
      .span12
        .twitter.span1
      .span12
        .facebook.span1
      

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar(type="button" data-toggle="collapse" data-target=".nav-collapse")
      .nav-collapse.collapse
        %ul.nav.navbar
          %li#properties
            = link_to('HOME', root_path)
          %li#neighborhoods
            = link_to('NOSOTROS', about_us_path)
          %li#about_us
            = link_to('PROPIEDADES', properties_path)
          %li#contact_us
            = link_to('CONTACTO', contact_path) 
      

app/views/layouts/_navigation_en.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar(type="button" data-toggle="collapse" data-target=".nav-collapse")
      .nav-collapse.collapse
        %ul.nav.navbar
          %li#properties
            = link_to('HOME', home_en_path)
          %li#neighborhoods
            = link_to('ABOUT US', about_us_en_path)
          %li#about_us
            = link_to('PROPERTIES', properties_en_index_path)
          %li#contact_us
            = link_to('CONTACT', contact_en_path) 
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : Settings.site_name
      %meta{:content => content_for?(:description) ? yield(:description) : Settings.site_name , :name => "description"}
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application"
      = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyAoAqRFSg4SPOGlkeJumobsLgCYKIAAEM0&sensor=false"
      = csrf_meta_tags
      = yield(:head)

  %body{:class => "#{controller_name} #{action_name}", :onload => "initialize()"}
    #header
      .row-fluid
        = link_to '', root_path, class: 'logo span2'
        .span5(style="margin-left:0px;")
          = link_to 'SIAN Group Properties', root_path, id: 'title'
        .span3(style="float:right")
          .lang
            .span12
              - if action_name == 'home_en' || action_name == 'about_us_en' || controller_name == 'properties_en' || action_name == 'contact_us_en'
                = link_to 'ESP', root_path
                = link_to 'ENG', home_en_path, class: 'select'
              - else
                = link_to 'ESP', root_path, class: 'select'
                = link_to 'ENG', home_en_path
            = semantic_form_for "", url: properties_path, :html => {:method => :get} do |f|
              .span7.codebox(style="margin-left:0px;")
                - if action_name == 'home_en' || action_name == 'about_us_en' || controller_name == 'properties_en' || action_name == 'contact_us_en'
                  = f.button :>
                  = f.input :code, :placeholder => "Code"
                - else
                  = f.button :>
                  = f.input :code, :placeholder => "Código"
    .row-fluid
      - if action_name == 'home_en' || action_name == 'about_us_en' || controller_name == 'properties_en' || action_name == 'contact_us_en'
        = render 'layouts/navigation_en'
      - else
        = render 'layouts/navigation'
    .row-fluid
      #main{:role => "main", :class => "#{action_name}"}
        - flash.each do |name, msg|
          - if msg.is_a?(String) 
            %div{:class => "alert alert-#{name == :alert ? "error" : "success"}"}
              %a.close{"data-dismiss" => "alert"} ×
              = content_tag :div, msg, :id => "flash_#{name}"
        = yield
    
    - if action_name == 'home_en' || action_name == 'about_us_en' || controller_name == 'properties_en' || action_name == 'contact_us_en'
      = render 'layouts/footer_en'
    - else
      = render 'layouts/footer'